### ISSUE TITLE
move cities to cloudkit

### ISSUE THREAD

**Issue by krishmittal21** [HouseRizz/HouseRizz-iOS#53]

**Comment by Kl0099** [comment]
Hi @krishmittal21,

I’m interested in working on this issue. Could you please provide more details on what needs to be done to move cities to CloudKit?

Thanks!

**Comment by krishmittal21** [comment]
Hey!
I am hard coding the cities Delhi, Agra to be used in the City Picker. They need to be inserted in CloudKit and have a separate record (like HRProduct etc)
